Repository LicenseRocks/rockskit, pull requests merged in 2022-08, with the labels that each got.

#114 feat(fileUpload): remove maxsize message if maxsize is not specified
  dist/rockskit.common.js
  dist/rockskit.common.js.map
  dist/rockskit.es.js
  dist/rockskit.es.js.map
  package.json
  src/Form/FileUpload/Dropzone.js
  src/Form/FileUpload/PreviewItem.js
  yarn.lock
Labels: enhancement

#115 fix/dropdown marketplace filter
  dist/rockskit.common.js
  dist/rockskit.common.js.map
  dist/rockskit.es.js
  dist/rockskit.es.js.map
  src/Dropdown/Dropdown.js
  src/Dropdown/stories.js
Labels: bug, enhancement

#117 Feat/background gradient
  dist/rockskit.common.js
  dist/rockskit.common.js.map
  dist/rockskit.es.js
  dist/rockskit.es.js.map
  package.json
  src/AppContainer/AppContainer.js
  src/theme/GlobalStyle.js
  src/theme/theme.js
Labels: enhancement

#116 feat: redesign dropdown api and logic
  dist/rockskit.common.js
  dist/rockskit.common.js.map
  dist/rockskit.es.js
  dist/rockskit.es.js.map
  package.json
  src/Button/Base/Base.js
  src/Button/Button/Button.js
  src/Button/OutlineButton/OutlineButton.js
  src/Button/TextButton/TextButton.js
  src/Button/stories.js
  src/Dropdown/Dropdown.js
  src/Dropdown/props.js
  src/Dropdown/stories.js
Labels: bug, enhancement

#120 fix/new dropdown
  dist/rockskit.common.js
  dist/rockskit.common.js.map
  dist/rockskit.es.js
  dist/rockskit.es.js.map
  package.json
  src/Dropdown/Dropdown.js
  src/Dropdown/props.js
  src/Dropdown/stories.js
  src/ProgressBar/ProgressBar.js
  src/ProgressBar/index.js
  src/ProgressBar/props.js
  src/ProgressBar/stories.js
Labels: bug

#128 fix(radioList): grid layout issue
  dist/rockskit.common.js
  dist/rockskit.common.js.map
  dist/rockskit.es.js
  dist/rockskit.es.js.map
  package.json
  src/Form/Fieldset/Fieldset.js
  src/Form/RadioExtra/RadioExtra.js
Labels: bug

#130 impprove errors messages for file types: application/*
  package.json
  src/Form/FileUpload/DropzoneError.js
Labels: enhancement

#131 feat: implement aspect ratio component with stories
  package.json
  src/AspectRatio/AspectRatio.js
  src/AspectRatio/index.js
  src/AspectRatio/stories.js
  src/index.js
Labels: enhancement
